AWSTemplateFormatVersion: '2010-09-09'
Description: Wild Rydes ECS App with CI/CD on AWS

Resources:

  WildRydesCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: wild-rydes-cluster

  WildRydesTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: wildRydesTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  WildRydesTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: wild-rydes-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt WildRydesTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: wild-rydes-container
          Image: YOUR_DOCKER_IMAGE_URI
          PortMappings:
            - ContainerPort: 80

  WildRydesService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref WildRydesCluster
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-0e123abc456de789f    
            - subnet-0e123abc456def456
          SecurityGroups:
            - sg-abc123          
      TaskDefinition: !Ref WildRydesTaskDefinition

Outputs:
  ClusterName:
    Value: !Ref WildRydesCluster
  TaskDefinition:
    Value: !Ref WildRydesTaskDefinition
