name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 985539801799.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Docker Image
      run: |
        docker build -t wild-rydes-app .
        docker tag wild-rydes-app:latest 985539801799.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app
        docker push 985539801799.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app

    - name: Deploy ECS
      run: |
        aws ecs update-service --cluster wild-rydes-cluster --service wild-rydes-service --force-new-deployment
